language: python
python:
  - "2.6"
  - "2.7"
install:
  - apt-get install nagios3 check-mk-livestatus pnp4nagios
  - pip install -r requirements.txt
  - python setup.py build
  - python setup.py install
  - pynag config --append "broker_module=/usr/lib/check_mk/livestatus.o /var/lib/nagios3/rw/livestatus"
  - mkdir -p /etc/nagios3/adagios
  - pynag config --append cfg_dir=/etc/nagios3/adagios
  - cd /etc/nagios3/
  - git init
  - git add .
  - git commit -a -m "Initial commit"
  - chown -R nagios /etc/nagios3 /etc/adagios
  - cd -
  - cd adagios
  - python manage.py test
  - echo "success"

before_script:
  - env
  - git config --global user.email "noreply@travis-ci.org"
  - git config --global user.name "Travis"
notifications:
  email: false

