language: python
python:
  - "2.6"
  - "2.7"
install:
  - sudo apt-get update
  - sudo apt-get install nagios3 check-mk-livestatus pnp4nagios python-simplejson python-django -y
  - pip install -r requirements.txt
  - sudo python setup.py build
  - sudo python setup.py install
  - sudo pynag config --append "broker_module=/usr/lib/check_mk/livestatus.o /var/lib/nagios3/rw/livestatus"
  - sudo mkdir -p /etc/nagios3/adagios
  - sudo pynag config --append cfg_dir=/etc/nagios3/adagios
  - cd /etc/nagios3/
  - sudo git init
  - sudo git add .
  - sudo git commit -a -m "Initial commit"
  - sudo chown -R nagios /etc/nagios3 /etc/adagios
  - cd -
  - cd adagios
  - sudo python manage.py test
  - echo "success"

before_script:
  - env
  - git config --global user.email "noreply@travis-ci.org"
  - git config --global user.name "Travis"
notifications:
  email: false

